# Generated by Django 5.1 on 2024-10-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_guidecommnets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guidecommnets',
            options={'verbose_name_plural': 'Guide_comments'},
        ),
    ]
