# Generated by Django 5.1.1 on 2024-10-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_page', '0011_registerstudent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerstudent',
            name='user',
        ),
    ]
