# Generated by Django 5.1.2 on 2024-11-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_page', '0012_remove_registerstudent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerstudent',
            name='Class',
            field=models.CharField(default='00', max_length=20),
        ),
    ]
