# Generated by Django 5.1.1 on 2024-10-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_additionalfile_user_codefile_user_databasefile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalfile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='codefile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='databasefile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='user',
        ),
    ]
