# Generated by Django 5.1.1 on 2024-10-10 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_additionalfile_user_remove_codefile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfile',
            name='content',
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(upload_to='uploads/document/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx'])]),
        ),
    ]
