# Generated by Django 5.1.1 on 2024-10-11 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_documentfile_content_alter_documentfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalfile',
            name='content',
        ),
        migrations.AlterField(
            model_name='additionalfile',
            name='file',
            field=models.FileField(upload_to='uploads/additional/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi'])]),
        ),
    ]
