# Generated by Django 5.1 on 2024-10-13 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_additionalfile_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfile',
            name='file',
            field=models.FileField(upload_to='uploads/additional/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi', 'jfif'])]),
        ),
    ]
