# Generated by Django 5.1.2 on 2024-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_reference_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='linkName',
            field=models.CharField(default='blank', max_length=50),
        ),
    ]
