# Generated by Django 4.2.30 on 2026-09-25 06:04

from django.conf import settings
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pathlib
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=30, unique=True)),
                (
                    "invite_code",
                    models.CharField(
                        default=projects.models.generate_invite_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="One sentence that sells the project.",
                        max_length=160,
                    ),
                ),
                ("abstract", models.TextField(blank=True)),
                (
                    "tech_stack",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated, e.g. Django, React, SQLite",
                        max_length=200,
                    ),
                ),
                (
                    "demo_url",
                    models.URLField(
                        blank=True, help_text="Optional live demo or video link"
                    ),
                ),
                ("cover", models.ImageField(blank=True, upload_to="covers/")),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("MI", "Mini project"),
                            ("MN", "Minor project"),
                            ("MA", "Major project"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "semester",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Semester 1"), (2, "Semester 2")]
                    ),
                ),
                (
                    "batch_year",
                    models.PositiveSmallIntegerField(
                        help_text="Academic year the project runs in, e.g. 2025"
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("COMPS", "Computer Engineering"),
                            ("IT", "Information Technology"),
                            ("AIDS", "AI & Data Science"),
                            ("EXTC", "Electronics & Telecom"),
                        ],
                        max_length=10,
                    ),
                ),
                ("group_number", models.PositiveSmallIntegerField(editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("building", "In progress"),
                            ("completed", "Completed"),
                        ],
                        default="planning",
                        max_length=12,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Show the showcase page on Explore"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guide",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "guide"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guided_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Path inside the project, e.g. src/app.py",
                        max_length=255,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=400,
                        storage=django.core.files.storage.FileSystemStorage(
                            location=pathlib.PureWindowsPath(
                                "C:/Users/Kushal/Documents/kushal soni/college folder/projecthub/Project_hub/private_media"
                            )
                        ),
                        upload_to=projects.models.vault_upload_to,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Decoded text for text files", null=True
                    ),
                ),
                ("size", models.PositiveIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_latest", models.BooleanField(db_index=True, default=True)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="What changed in this version",
                        max_length=160,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["path", "-version"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_lead", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="projects.project",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=5
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="showcase/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                    "jfif",
                                    "mp4",
                                    "webm",
                                    "mov",
                                ]
                            )
                        ],
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=140)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line", models.PositiveIntegerField(blank=True, null=True)),
                ("body", models.TextField()),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.projectfile",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="projectfile",
            index=models.Index(
                fields=["project", "path"], name="projects_pr_project_251b0c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("project", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("project", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together={("project", "user")},
        ),
    ]
